set(TEST_NAMES
  assertions
  spsc_bounded_disconnect_sender
  spsc_bounded_disconnect_receiver
  spsc_bounded_one_item
  spsc_bounded_two_seperate
  spsc_bounded_two_consecutive
  spsc_bounded_leftover
  spsc_bounded_try
  spsc_bounded_one_to_one_disconnect_sender
  spsc_bounded_one_to_one_disconnect_sender_buffer_size_1
  spsc_bounded_one_to_one_disconnect_receiver
  spsc_bounded_one_to_one_disconnect_receiver_buffer_size_1
  spsc_unbounded_disconnect_sender
  spsc_unbounded_disconnect_receiver
  spsc_unbounded_one_item
  spsc_unbounded_two_seperate
  spsc_unbounded_two_consecutive
  spsc_unbounded_leftover
  spsc_unbounded_try
  spsc_unbounded_one_to_one_disconnect_sender
  spsc_unbounded_one_to_one_disconnect_sender_chunk_size_1
  spsc_unbounded_one_to_one_disconnect_receiver
  spsc_unbounded_one_to_one_disconnect_receiver_chunk_size_1
  spsc_unbuffered_disconnect_sender
  spsc_unbuffered_disconnect_receiver
  spsc_unbuffered_try
  spsc_unbuffered_one_to_one_disconnect_sender
  spsc_unbuffered_one_to_one_disconnect_receiver
  mpsc_bounded_disconnect_sender
  mpsc_bounded_disconnect_receiver
  mpsc_bounded_one_item
  mpsc_bounded_two_seperate
  mpsc_bounded_two_consecutive
  mpsc_bounded_leftover
  mpsc_bounded_try
  mpsc_bounded_one_to_one_disconnect_sender
  mpsc_bounded_one_to_one_disconnect_sender_buffer_size_1
  mpsc_bounded_one_to_one_disconnect_receiver
  mpsc_bounded_one_to_one_disconnect_receiver_buffer_size_1
  mpsc_bounded_many_to_one_disconnect_sender
  mpsc_bounded_many_to_one_disconnect_sender_buffer_size_1
  mpsc_bounded_many_to_one_disconnect_receiver
  mpsc_bounded_many_to_one_disconnect_receiver_buffer_size_1
  mpsc_bounded_add_remove_sender
  mpsc_unbounded_disconnect_sender
  mpsc_unbounded_disconnect_receiver
  mpsc_unbounded_one_item
  mpsc_unbounded_two_seperate
  mpsc_unbounded_two_consecutive
  mpsc_unbounded_leftover
  mpsc_unbounded_try
  mpsc_unbounded_one_to_one_disconnect_sender
  mpsc_unbounded_one_to_one_disconnect_sender_chunk_size_1
  mpsc_unbounded_one_to_one_disconnect_receiver
  mpsc_unbounded_one_to_one_disconnect_receiver_chunk_size_1
  mpsc_unbounded_many_to_one_disconnect_sender
  mpsc_unbounded_many_to_one_disconnect_sender_chunk_size_1
  mpsc_unbounded_many_to_one_disconnect_receiver
  mpsc_unbounded_many_to_one_disconnect_receiver_chunk_size_1
  mpsc_unbounded_add_remove_sender
  mpsc_unbuffered_disconnect_sender
  mpsc_unbuffered_disconnect_receiver
  mpsc_unbuffered_try
  mpsc_unbuffered_one_to_one_disconnect_sender
  mpsc_unbuffered_one_to_one_disconnect_receiver
  mpsc_unbuffered_many_to_one_disconnect_sender
  mpsc_unbuffered_many_to_one_disconnect_receiver
  mpsc_unbuffered_add_remove_sender
  spmc_bounded_disconnect_sender
  spmc_bounded_disconnect_receiver
  spmc_bounded_one_item
  spmc_bounded_two_seperate
  spmc_bounded_two_consecutive
  spmc_bounded_leftover
  spmc_bounded_try
  spmc_bounded_one_to_one_disconnect_sender
  spmc_bounded_one_to_one_disconnect_sender_buffer_size_1
  spmc_bounded_one_to_one_disconnect_receiver
  spmc_bounded_one_to_one_disconnect_receiver_buffer_size_1
  spmc_bounded_one_to_many_disconnect_sender
  spmc_bounded_one_to_many_disconnect_sender_buffer_size_1
  spmc_bounded_one_to_many_disconnect_receiver
  spmc_bounded_one_to_many_disconnect_receiver_buffer_size_1
  spmc_bounded_add_remove_receiver
  spmc_unbounded_disconnect_sender
  spmc_unbounded_disconnect_receiver
  spmc_unbounded_one_item
  spmc_unbounded_two_seperate
  spmc_unbounded_two_consecutive
  spmc_unbounded_leftover
  spmc_unbounded_try
  spmc_unbounded_one_to_one_disconnect_sender
  spmc_unbounded_one_to_one_disconnect_sender_chunk_size_1
  spmc_unbounded_one_to_one_disconnect_receiver
  spmc_unbounded_one_to_one_disconnect_receiver_chunk_size_1
  spmc_unbounded_one_to_many_disconnect_sender
  spmc_unbounded_one_to_many_disconnect_sender_chunk_size_1
  spmc_unbounded_one_to_many_disconnect_receiver
  spmc_unbounded_one_to_many_disconnect_receiver_chunk_size_1
  spmc_unbounded_add_remove_receiver
  spmc_unbuffered_disconnect_sender
  spmc_unbuffered_disconnect_receiver
  spmc_unbuffered_try
  spmc_unbuffered_one_to_one_disconnect_sender
  spmc_unbuffered_one_to_one_disconnect_receiver
  spmc_unbuffered_one_to_many_disconnect_sender
  spmc_unbuffered_one_to_many_disconnect_receiver
  spmc_unbuffered_add_remove_receiver
  mpmc_bounded_disconnect_sender
  mpmc_bounded_disconnect_receiver
  mpmc_bounded_one_item
  mpmc_bounded_two_seperate
  mpmc_bounded_two_consecutive
  mpmc_bounded_leftover
  mpmc_bounded_try
  mpmc_bounded_one_to_one_disconnect_sender
  mpmc_bounded_one_to_one_disconnect_sender_buffer_size_1
  mpmc_bounded_one_to_one_disconnect_receiver
  mpmc_bounded_one_to_one_disconnect_receiver_buffer_size_1
  mpmc_bounded_many_to_one_disconnect_sender
  mpmc_bounded_many_to_one_disconnect_sender_buffer_size_1
  mpmc_bounded_many_to_one_disconnect_receiver
  mpmc_bounded_many_to_one_disconnect_receiver_buffer_size_1
  mpmc_bounded_one_to_many_disconnect_sender
  mpmc_bounded_one_to_many_disconnect_sender_buffer_size_1
  mpmc_bounded_one_to_many_disconnect_receiver
  mpmc_bounded_one_to_many_disconnect_receiver_buffer_size_1
  mpmc_bounded_many_to_many_disconnect_sender
  mpmc_bounded_many_to_many_disconnect_sender_buffer_size_1
  mpmc_bounded_many_to_many_disconnect_receiver
  mpmc_bounded_many_to_many_disconnect_receiver_buffer_size_1
  mpmc_bounded_add_remove_sender
  mpmc_bounded_add_remove_receiver
  mpmc_bounded_add_remove_sender_receiver
  mpmc_unbounded_disconnect_sender
  mpmc_unbounded_disconnect_receiver
  mpmc_unbounded_one_item
  mpmc_unbounded_two_seperate
  mpmc_unbounded_two_consecutive
  mpmc_unbounded_leftover
  mpmc_unbounded_try
  mpmc_unbounded_one_to_one_disconnect_sender
  mpmc_unbounded_one_to_one_disconnect_sender_chunk_size_1
  mpmc_unbounded_one_to_one_disconnect_receiver
  mpmc_unbounded_one_to_one_disconnect_receiver_chunk_size_1
  mpmc_unbounded_many_to_one_disconnect_sender
  mpmc_unbounded_many_to_one_disconnect_sender_chunk_size_1
  mpmc_unbounded_many_to_one_disconnect_receiver
  mpmc_unbounded_many_to_one_disconnect_receiver_chunk_size_1
  mpmc_unbounded_one_to_many_disconnect_sender
  mpmc_unbounded_one_to_many_disconnect_sender_chunk_size_1
  mpmc_unbounded_one_to_many_disconnect_receiver
  mpmc_unbounded_one_to_many_disconnect_receiver_chunk_size_1
  mpmc_unbounded_many_to_many_disconnect_sender
  mpmc_unbounded_many_to_many_disconnect_sender_chunk_size_1
  mpmc_unbounded_many_to_many_disconnect_receiver
  mpmc_unbounded_many_to_many_disconnect_receiver_chunk_size_1
  mpmc_unbounded_add_remove_sender
  mpmc_unbounded_add_remove_receiver
  mpmc_unbounded_add_remove_sender_receiver
  mpmc_unbuffered_disconnect_sender
  mpmc_unbuffered_disconnect_receiver
  mpmc_unbuffered_try
  mpmc_unbuffered_one_to_one_disconnect_sender
  mpmc_unbuffered_one_to_one_disconnect_receiver
  mpmc_unbuffered_many_to_one_disconnect_sender
  mpmc_unbuffered_many_to_one_disconnect_receiver
  mpmc_unbuffered_one_to_many_disconnect_sender
  mpmc_unbuffered_one_to_many_disconnect_receiver
  mpmc_unbuffered_many_to_many_disconnect_sender
  mpmc_unbuffered_many_to_many_disconnect_receiver
  mpmc_unbuffered_add_remove_sender
  mpmc_unbuffered_add_remove_receiver
  mpmc_unbuffered_add_remove_sender_receiver
)

add_subdirectory(test_util)

foreach(test_name IN LISTS TEST_NAMES)
  add_executable(${test_name} ${test_name}.cpp)
  target_link_libraries(${test_name} chan test_util)
  add_test(NAME ${test_name} COMMAND ${test_name})
endforeach()
